In [30]:
'''
矩阵与二维数组，下标返回值的区别。
'''
m1 = np.array ( [
    [ 1, 2, 3, 4],
    [ 5, 6, 7, 8]
] )

m2 = np.matrix ( [
    [ 1, 2, 3, 4],
    [ 5, 6, 7, 8]
] )

print ( m1 [0] )    #返回的不在是二维，而是一维数组
print ( m2 [0] )   #返回的还是二维数组


[1 2 3 4]
[[1 2 3 4]]


In [31]:
#矩阵的迭代
for  row in m2:
    print ( row )

[[1 2 3 4]]
[[5 6 7 8]]
